name: Angular - Pockedeck Battler

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
        working-directory: PockedeckBattler.Angular
      - run: npm test:ci
        working-directory: PockedeckBattler.Angular
